from flask import Flask, Response, jsonify, render_template_string, request
import asyncio
import aiohttp
import threading
import time
import os
import logging
from collections import OrderedDict
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ==================== CONFIG ====================
SOURCES = [
    ("https://iptv-org.github.io/iptv/countries/ru.m3u", 100),
    ("https://iptv-org.github.io/iptv/countries/ru_general.m3u", 95),
    ("https://m3u.su/m3u/sng.m3u", 90),
    ("https://m3u.su/m3u/world.m3u", 85),
    ("https://raw.githubusercontent.com/iptv-org/iptv/master/channels.m3u", 80),
    ("https://raw.githubusercontent.com/DenMSU/tv/main/tv.m3u", 75),
    ("https://raw.githubusercontent.com/sknk/iptv/master/kvas.m3u", 70),
    ("https://webarmen.com/my/iptv/auto.nogeo.m3u", 65),
    ("https://raw.githubusercontent.com/4mirror/iptv/master/ru.m3u", 60),
    ("https://raw.githubusercontent.com/alexeyvaneev/iptv/master/ru.m3u", 55),
]

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
}

CACHE_DURATION = 1800  # 30 минут
playlist_cache = "#EXTM3U\n# Generated by IPTV Aggregator Pro\n"
cache_timestamp = 0
stats = {"total_channels": 0, "sources_processed": 0, "last_update": ""}

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ==================== ASYNC FETCHER ====================
async def fetch_playlist(session, url, priority):
    try:
        async with session.get(url, timeout=20, headers=HEADERS) as resp:
            if resp.status != 200:
                return []
            text = await resp.text()
            return parse_m3u(text, priority)
    except Exception as e:
        logger.warning(f"Failed {url}: {e}")
        return []


def parse_m3u(content: str, priority: int):
    channels = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("#EXTINF:"):
            # Извлекаем tvg-name, tvg-id, group-title и название
            inf = line
            tvg_name = None
            tvg_id = None
            group = "Other"

            if 'tvg-name="' in inf:
                tvg_name = inf.split('tvg-name="')[1].split('"')[0]
            if 'tvg-id="' in inf:
                tvg_id = inf.split('tvg-id="')[1].split('"')[0]
            if 'group-title="' in inf:
                group = inf.split('group-title="')[1].split('"')[0]

            name = tvg_name or inf.split(',')[-1].strip()

            i += 1
            if i < len(lines) and lines[i].strip().startswith("http"):
                url = lines[i].strip()
                channels.append({
                    "url": url,
                    "inf": inf,
                    "name": name,
                    "tvg_id": tvg_id,
                    "tvg_name": tvg_name,
                    "group": group,
                    "priority": priority
                })
        i += 1
    return channels


async def update_cache():
    global playlist_cache, cache_timestamp, stats
    start = time.time()

    async with aiohttp.ClientSession() as session:
        tasks = [fetch_playlist(session, url, prio) for url, prio in SOURCES]
        results = await asyncio.gather(*tasks, return_exceptions=True)

    # Умная дедупликация
    seen = OrderedDict()
    for result in results:
        if isinstance(result, Exception):
            continue
        for ch in result:
            key = (ch["tvg_id"] or ch["tvg_name"] or ch["url"], ch["url"])
            if key not in seen or ch["priority"] > seen[key]["priority"]:
                seen[key] = ch

    # Сборка плейлиста
    lines = ["#EXTM3U", f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}", 
             f"# Total channels: {len(seen)}"]
    
    for ch in seen.values():
        lines.append(ch["inf"])
        lines.append(ch["url"])

    playlist_cache = "\n".join(lines)
    cache_timestamp = time.time()
    
    stats.update({
        "total_channels": len(seen),
        "sources_processed": len([r for r in results if not isinstance(r, Exception)]),
        "last_update": time.strftime("%Y-%m-%d %H:%M:%S")
    })
    
    logger.info(f"Cache updated: {len(seen)} channels in {time.time()-start:.1f}s")


def background_updater():
    while True:
        try:
            asyncio.run(update_cache())
        except Exception as e:
            logger.error(f"Updater error: {e}")
        time.sleep(CACHE_DURATION)


# ==================== ROUTES ====================
@app.route('/')
def home():
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>IPTV Aggregator Pro</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; background: #0f0f23; color: #0f0; padding: 20px; }}
            .card {{ background: #1a1a2e; border-radius: 12px; padding: 20px; margin: 15px 0; }}
            h1 {{ color: #00ff9d; }}
            .stat {{ font-size: 1.4em; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>IPTV Aggregator Pro</h1>
        <div class="card">
            <div class="stat">Каналов: {stats["total_channels"]}</div>
            <div>Последнее обновление: {stats["last_update"]}</div>
            <div>Обработано источников: {stats["sources_processed"]}</div>
        </div>
        <a href="/playlist.m3u" style="color:#00ff9d;font-size:1.2em">Скачать плейлист (.m3u)</a><br><br>
        <a href="/api/channels" style="color:#00ff9d">JSON API каналов</a>
    </body>
    </html>
    """
    return render_template_string(html)


@app.route('/playlist.m3u')
@app.route('/iptv.m3u')
def get_playlist():
    if time.time() - cache_timestamp > CACHE_DURATION + 300:
        threading.Thread(target=lambda: asyncio.run(update_cache()), daemon=True).start()
    return Response(playlist_cache, mimetype='application/vnd.apple.mpegurl')


@app.route('/api/channels')
def api_channels():
    # Простой парсинг для API
    channels = []
    for line in playlist_cache.splitlines():
        if line.startswith("#EXTINF:"):
            name = line.split(',')[-1].strip() if ',' in line else "Unknown"
            channels.append({"name": name})
    return jsonify({"channels": channels[:500], "total": stats["total_channels"]})  # лимит для удобства


@app.route('/health')
def health():
    return jsonify({
        "status": "healthy",
        "channels": stats["total_channels"],
        "uptime_seconds": int(time.time() - cache_timestamp)
    })


# ==================== START ====================
if __name__ == '__main__':
    # Первый запуск
    logger.info("Starting IPTV Aggregator Pro...")
    threading.Thread(target=background_updater, daemon=True).start()
    
    # Даём время на первый сбор
    time.sleep(8)
    
    app.run(host='0.0.0.0', port=10000, debug=False)
